### PR TITLE
harden World unique object handling

### PR DESCRIPTION
**Pull request by evaleev**
`World::id_to_ptr()` return an optional; if `NDEBUG` is not defined then its value for deregistered IDs is nullptr, this can be used to detect use of unregistered/deleted objects.

### CODE REVIEW

**Comment by robertjharrison** [comment]
Interesting ... what's driving this?

**Comment by evaleev** [comment]
> Interesting ... what's driving this?

larger jobs (with hundreds of thousands of expression elements, involving thousands of tiles each) are getting stuck stochastically (but with near 100% probability) due to lack of progress. I thought maybe a lifetime issue (pulling from temporary objects, e.g. subexpressions), but does not seem to be that. Expression evaluation actually pushes data up, which makes lifetime management easier. TA expression cleanup does not use global fencing, only local info, and push makes it possible.

**Comment by evaleev** [comment]
@robertjharrison I don't think I made any perf-related changes here, but if you see something amiss let me know.

**Comment by robertjharrison** [comment]
Is there an issue with ordering or tasks internally forcing futures?  Or
use of send instead of task?

Grasping at straws in the absence of info.

**Review by evaleev — COMMENTED** [review]
approved

**Pull request merged**
