### PR TITLE
remove fxc_old

### PR DESCRIPTION
**Pull request by jeffhammond**
Assuming Travis signs off on this, this will remove the `fxc_old` function that @naromero77 is concerned about.

### CODE REVIEW

**Comment by robertjharrison** [comment]
I think fxc_old is now being used by Bryan as an interim to merging
Alvaro's TDDFT implementation with Florian's/Jakob's ... the xc_functional
class was rejiggerred during the branch and the merge in underway.

Bryan ... can U please comment?

On Fri, Apr 8, 2016 at 4:23 PM, Jeff Hammond <notifications@github.com>
wrote:

> Assuming Travis signs off on this, this will remove the fxc_old function
> that @naromero77 <https://github.com/naromero77> is concerned about.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/m-a-d-n-e-s-s/madness/pull/189
> Commit Summary
>
>    - remove fxc_old
>
> File Changes
>
>    - *M* src/apps/chem/xcfunctional.h
>    <https://github.com/m-a-d-n-e-s-s/madness/pull/189/files#diff-0> (3)
>    - *M* src/apps/chem/xcfunctional_libxc.cc
>    <https://github.com/m-a-d-n-e-s-s/madness/pull/189/files#diff-1> (230)
>
> Patch Links:
>
>    - https://github.com/m-a-d-n-e-s-s/madness/pull/189.patch
>    - https://github.com/m-a-d-n-e-s-s/madness/pull/189.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/pull/189>
>



-- 
Robert J. Harrison
tel:  865-272-9262

**Comment by bsundahl** [comment]
I am reimplementing code that uses fxc_old. Once I'm done verifying that I
get the same correct results as an older version I will submit a pull
request to merge it back in.

**Comment by jeffhammond** [comment]
"git grep" says it is not used in master...

>

-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Comment by jeffhammond** [comment]
In any case, the implementation of `fxc_old` is inconsistent with its declaration, so no one should use it until it is rewritten.  Frankly, this code should be deleted in order to force someone to implement it from scratch so as to have some hope of being correct.

# Function Declaration

The declaration of this function uses an enum, which can take the values 1-6 (according to C99, [via StackOverflow](http://stackoverflow.com/a/30312219/2189128)).
```c++
    madness::Tensor<double> fxc_old(const std::vector< madness::Tensor<double> >& t,
            const int ispin, const xc_contribution xc_contrib) const;
```
where
```c++
    enum xc_contribution {
        potential_rho,              // potential df/drho
        potential_same_spin,        // potential df/dsigma_aa
        potential_mixed_spin,       // potential df/dsigma_ab
        kernel_second_local,        // kernel (2nd derivative)
        kernel_second_semilocal,    // kernel (2nd derivative)
        kernel_first_semilocal      // kernel (2nd derivative)
    };
```

# Function Definition / Implementation
The implementation of this function uses integers that do not correspond to the enum, and it is not even clear that the cases where the integer values of `what` correspond to valid enumerations are mapped correctly.
```c++
madness::Tensor<double> XCfunctional::fxc_old(const std::vector< madness::Tensor<double> >& t,
        const int ispin, const xc_contribution what) const {
...
    if(what ==99){
...
```

**Comment by jeffhammond** [comment]
Sorry @bsundahl, I responded before I saw your post.  I'm glad to hear that you are reimplementing this function.

**Comment by fbischoff** [comment]
I implemented the fxc_apply to replace fxc/fxc_old fairly recently, because the derivatives of the xc potential are very noisy. I don’t know if fxc ever worked properly for anything else than LDA. In fxc_apply the kernel is applied directly on its argument with the aim of reducing the noise. 

I think fxc_old should be removed. I stopped working on this (as I stopped working on the munging) because we wanted to check for the correctness of libxc first.

**Comment by v4m4** [comment]
Bryan, could you use fxc_apply instead?
For our purposes, we will use LDA only, then we will merge my changes to
fix the XC functionals. We also need a kxc_apply.

**Comment by bsundahl** [comment]
We can definitely move in that direction. Removing fxc_old can be done now.

**Pull request merged**
