### PR TITLE
C++11 atomics and other attempts at portability

### PR DESCRIPTION
**Pull request by jeffhammond**
I am well aware that I can commit directly, but I want someone to review these commits for correctness and make sure they run through Jenkins.

### CODE REVIEW

**Comment by jeffhammond** [comment]
@justusc Is there any way that you can review this and merge if appropriate?  I recall seeing on the Wiki that you are the maintainer for the parallel runtime.

I have no urgent need for this but it would be nice to close this issue now while it is still in cache for both of us :-)

**Comment by justusc** [comment]
The code and CI tests look OK. The only thing that makes me nervous about the commit is that it does not check specific compiler versions. GCC 4.8, Intel 13, and Clang 3.3 are the minimum required versions (I think). This avoid problems with GCC 4.7 on BG/Q.

**Comment by naromero77** [comment]
Please do not make it harder to compile MADNESS on BG/Q. We may have newer
version of GCC on BG/Q in the near future, but this will be if William
Scullin gets it working.

On Tue, Aug 4, 2015 at 1:56 PM, Justus Calvin <notifications@github.com>
wrote:

> The code and CI tests look OK. The only thing that makes me nervous about
> the commit is that it does not check specific compiler versions. GCC 4.8,
> Intel 13, and Clang 3.3 are the minimum required versions (I think). This
> avoid problems with GCC 4.7 on BG/Q.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/pull/150#issuecomment-127716420>
> .
>



-- 
Nichols A. Romero, Ph.D.

**Comment by robertjharrison** [comment]
I assume this all works with a current version of LLVM/clang?   I am asking
for Power8/9 compatibility ... XLC is also of interest but as long as clang
works we should be OK


http://llvm.org/devmtg/2014-04/PDFs/Talks/Euro-LLVM-2014-Weigand.pdf

On Tue, Aug 4, 2015 at 4:14 PM, Nichols A. Romero <notifications@github.com>
wrote:

> Please do not make it harder to compile MADNESS on BG/Q. We may have newer
> version of GCC on BG/Q in the near future, but this will be if William
> Scullin gets it working.
>
> On Tue, Aug 4, 2015 at 1:56 PM, Justus Calvin <notifications@github.com>
> wrote:
>
> > The code and CI tests look OK. The only thing that makes me nervous about
> > the commit is that it does not check specific compiler versions. GCC 4.8,
> > Intel 13, and Clang 3.3 are the minimum required versions (I think). This
> > avoid problems with GCC 4.7 on BG/Q.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/m-a-d-n-e-s-s/madness/pull/150#issuecomment-127716420>
> > .
> >
>
>
>
> --
> Nichols A. Romero, Ph.D.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/pull/150#issuecomment-127743285>
> .
>



-- 
Robert J. Harrison
tel:  865-272-9262

**Comment by robertjharrison** [comment]
I agree with Nick that we need to make sure things keep working on the BG.

Also, rather than checking for compiler versions should we not be checking
for features using the usual autoconf scripts ... this seems to be less
error prone and is consistent with how we are managing other functionality.

On Tue, Aug 4, 2015 at 4:14 PM, Nichols A. Romero <notifications@github.com>
wrote:

> Please do not make it harder to compile MADNESS on BG/Q. We may have newer
> version of GCC on BG/Q in the near future, but this will be if William
> Scullin gets it working.
>
> On Tue, Aug 4, 2015 at 1:56 PM, Justus Calvin <notifications@github.com>
> wrote:
>
> > The code and CI tests look OK. The only thing that makes me nervous about
> > the commit is that it does not check specific compiler versions. GCC 4.8,
> > Intel 13, and Clang 3.3 are the minimum required versions (I think). This
> > avoid problems with GCC 4.7 on BG/Q.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/m-a-d-n-e-s-s/madness/pull/150#issuecomment-127716420>
> > .
> >
>
>
>
> --
> Nichols A. Romero, Ph.D.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/pull/150#issuecomment-127743285>
> .
>



-- 
Robert J. Harrison
tel:  865-272-9262

**Comment by jeffhammond** [comment]
@justusc Thanks.  I will add the specific compiler version checks to which you allude.  I know how to do that.  Thanks for the reminder.

@naromero77 I will add a check so that this code is never used on Blue Gene/Q.  Note that this is already covered if I test for GCC 4.8 but I will be explicitly with `!defined(__bgq__)` to be sure.

@robertjharrison Because C++11 compiler features are known to be buggy, it is not sufficient to do compilation-only configure testing.  I will write the preprocessor solution.  Someone else is welcome to create an configure solution to replace it.

@robertjharrison Unfortunately, my POWER9 order has not yet been fulfilled :-)  As for POWER8, I don't know, but I don't see why C++11 atomics should be any _worse_ than GCC atomics.  I have some knowledge of TBB on POWER8 little-endian that may be relevant but I prefer to discuss it offline (because I am not sure about the cause of what is observed and do not want to falsely pin the blame on IBM).

**Pull request merged**
