### PR TITLE
Nonblocking

### PR DESCRIPTION
**Pull request by kimjsung**

### CODE REVIEW

**Comment by justusc** [comment]
Can you provide a brief description of the content of this pull request?

**Comment by kimjsung** [comment]
This is my updates for FuseT working with Samyam.
This is related to "madness/src/examples/FuseTExamples" and "madness/src/madness/mra/FuseT".
Furthermore, it modified temporally mraimpl.h (madness/src/madness/mra).

**Comment by naromero77** [comment]
What is FuseT?


On Tue, Feb 16, 2016 at 4:25 PM, kimjsung <notifications@github.com> wrote:

> This is my updates for FuseT working with Samyam.
> This is related to "madness/src/examples/FuseTExamples" and
> "madness/src/madness/mra/FuseT".
> Furthermore, it modified temporally mraimpl.h (madness/src/madness/mra).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/m-a-d-n-e-s-s/madness/pull/181#issuecomment-184899835>
> .
>



-- 
Nichols A. Romero, Ph.D.

**Comment by kimjsung** [comment]
FuseT implements fused operators for MADNESS.

**Comment by kimjsung** [comment]
Oh I am really sorry. I pull the incorrect repository..

**Pull request closed without merging**
