### PR TITLE
Pullreq cc2

### PR DESCRIPTION
**Pull request by kottmanj**
Added CC2 GS/Response Code including additional code in the MRAlib.

### CODE REVIEW

**Comment by robertjharrison** [comment]
Sorry to have again been slow ... I had started going thru all of the
changes to the mra directory but did not have chance to complete this.
Overall things looked ok but there seemed to be more f12 specific stuff
injected into the mra core header files.

I would rather we precede such changes in the core with a design discussion
and also that the changes sets be smaller where possibe.  Both would leave
us all understanding the code better and with a more consistent design
throughout.



On Jan 27, 2017 7:16 AM, "fbischoff" <notifications@github.com> wrote:

Merged #231 <https://github.com/m-a-d-n-e-s-s/madness/pull/231>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/m-a-d-n-e-s-s/madness/pull/231#event-939205319>, or mute
the thread

**Comment by fbischoff** [comment]
This pull request is indeed a lot of code, but we have put all the mralib changes in one commit (6a62c62). They are almost exclusively concerned with the way fill_tree determines boxes to be leaves. We can try to merge the fill_tree methods in mra.h into one or two. Then the f12 specialization is encapsulated in leafop.h.

**Comment by robertjharrison** [comment]
Looks good for now.

When Jakob visits he can help me understand your objectives and we can work
to clean up the design and code throughout .

A major reimplementation of everything is looming and when I get a complete
design sketched out we can start to discuss that.  But that is probably not
until late spring.

**Comment by fbischoff** [comment]
That would be great! I am well aware that I also have introduced some unnecessary code over the years that I would also like to clean up. I hope I will be able to remove some dead wood from the code soon so that we don’t have to be concerned about that during the refactoring.

**Pull request merged**
