### PR TITLE
Fix to concat0

### PR DESCRIPTION
**Pull request by EricaCMitchell**
This PR addresses Issue #551 

Original code from commit c7e2673978583334a2a9b555477642ccdc601764 allowed nullptr for buf0 and buf1.

Fixes construction of unique_ptr and ensures buffer size `bufsz` is a multiple of alignment `size_of(void*)`.

Was able to run `mpirun -n 6 moldft input` successfully on my machine with a total cpu time of 321.7s.

### CODE REVIEW

**Comment by evaleev** [comment]
@fbischoff please try

**Comment by fbischoff** [comment]
@evaleev <https://github.com/evaleev>   @EricaCMitchell <https://github.com/EricaCMitchell>

Unfortunately still not working (see stack trace below). 

The testsuite doesn’t test on multiple MPI processes, that I will change asap..


timer:        guess density     0.13s     0.13s
[xeonmax:1655495:0:1655495] Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))
==== backtrace (tid:1655495) ====
 0 0x000000000003e6f0 __GI___sigaction()  :0
 1 0x0000000000959ab3 madness::archive::BufferOutputArchive::store<unsigned long>()  SCF.cc:0
 2 0x0000000000993258 madness::WorldGopInterface::concat0<std::pair<madness::Key<3ul>, double> >()  ???:0
 3 0x00000000009a66d7 madness::LoadBalanceDeux<3ul>::load_balance()  ???:0
 4 0x0000000000973571 madness::SCF::initial_guess()  ???:0
 5 0x00000000008c188b madness::Nemo::value()  ???:0
 6 0x00000000008c7ca2 madness::Nemo::value()  ???:0
 7 0x00000000004939e3 main()  ???:0
 8 0x0000000000029590 __libc_start_call_main()  ???:0
 9 0x0000000000029640 __libc_start_main_alias_2()  :0
10 0x00000000004a2645 _start()  ???:0
=================================
--------------------------------------------------------------------------
prterun noticed that process rank 1 with PID 1655495 on node xeonmax exited on
signal 11 (Segmentation fault).

------------------------------------------------------
Florian Bischoff
Humboldt-Universitaet zu Berlin, Institut fuer Chemie
Unter den Linden 6, 10099 Berlin
phone: +49-30-2093-82708
office: Brook-Taylor-Str 2, room 3'322
***@***.***
https://tinyurl.com/bischofflab

**Comment by evaleev** [comment]
@fbischoff can an you please share input/metadata?

**Comment by fbischoff** [comment]
The error occurs both on mac and on the unix cluster, so I guess it’s universal. Here is a minimal example, no input file needed

cmake /path/to/patch
make -j moldft
cd src/apps/moldft
mpirun -np 2 moldft --geometry=he


------------------------------------------------------
Florian Bischoff
Humboldt-Universitaet zu Berlin, Institut fuer Chemie
Unter den Linden 6, 10099 Berlin
phone: +49-30-2093-82708
office: Brook-Taylor-Str 2, room 3'322
***@***.***
https://tinyurl.com/bischofflab

**Comment by evaleev** [comment]
@fbischoff runs fine for both of us. perhaps build issues on your side? can you please try https://github.com/m-a-d-n-e-s-s/madness/pull/553/commits/e74031795848946b34395015c4fe40ee7732cbfd again

**Review by evaleev — APPROVED** [review]

**Pull request merged**
